on:
  push:
    branches: [ master ]
  # workflow_dispatch:

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1

      # Automatically commits minified files to the repository
      - name: Committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic JS/CSS Minification"
          branch: ${{ github.ref }}